org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Environment Properties
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
## Mod Properties
mod_id=iceandfire
mod_name=Ice And Fire Community Edition
mod_license=LGPL-3.0
mod_version=2.2-beta.3
mod_group_id=com.iafenvoy.iceandfire
# Dependencies
emi_version=1.1.19+1.21.1
jei_version=29.29.0.77
ponder_version=1.0.61
integration_version=0.2
ars_version=5.10.3.1204
geckolib_version=4.7.7
curios_version=15.0.0+26.1.2
loader_version=0.19.5
fabric_api_version=0.161.0+26.3
modmenu_version=18.0.0-alpha.8
