org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)
## Mod Properties
mod_id=iceandfire
mod_name=Ice And Fire Community Edition
mod_license=LGPL-3.0
mod_version=2.1.3
mod_group_id=com.iafenvoy.iceandfire
# Dependencies
emi_version=1.1.19+1.21.1
jei_version=19.21.0.247
ponder_version=1.0.61
integration_version=0.2
ars_version=5.10.3.1204
geckolib_version=4.7.7
curios_version=9.5.1+1.21.1